-- Town quests batch 2 — Fort Ashveil, Mirepost, Sylvara, Dawnharbor, Tidecrest,
-- Cinderpost, Coldrun (Aranthor region) + Caldrath, Ironwatch, Stonefall, Iron Bastion (Darian Empire)

INSERT INTO quests (title, slug, region, quest_type, status, description, dm_notes, reward_notes) VALUES

-- FORT ASHVEIL
('The Surgeon''s List', 'fort-ashveil-surgeon', 'Aranthor', 'town', 'available',
 'Fort Ashveil''s garrison surgeon Adren Pyke has had the same three medical supply requests denied for three months. He mentions it to players with the casualness of someone hoping someone asks the right question.',
 'One of the denied supplies — sealwort paste — is for a prisoner in the cells, not the garrison. The prisoner is Elvan Crost, a Loyalist courier whose wound will kill him in a month without treatment. The rejecting officer has informal orders to let the detainment "conclude naturally" — no execution record, no court record. Crost knows a document cache location three factions want. Players who get Pyke the supply can reach Crost; he trades the cache location for extraction. Exposing the suppressed requisition disrupts one officer''s quiet authority without touching Fort command.',
 'Crost''s document cache location — connects to at least one main campaign thread. Pyke becomes a covert medical contact inside Fort Ashveil.'),

('The Wrong Flag', 'fort-ashveil-wrong-flag', 'Aranthor', 'town', 'available',
 'A woman named Grest Orvey has received a formal Blackwell intelligence summons. She is 61, a retired baker, and has no idea why. The original Grest Orvey — a genuine Loyalist contact — died three years ago. The file was never closed.',
 'A Blackwell records officer filed a "location confirmed" note six months ago based on a physical description match. The file is at Fort Ashveil: DC 13 Investigation to locate in the active-summons ledger, DC 10 to identify the discrepancy. Correcting it requires a clerk''s authorization — Fenwick (30, junior, has corrected two legitimate filing errors and takes quiet pride in it) will process it if players present it as a third filing error rather than a cover-up. DC 14 Persuasion, or automatic with clear documentation. The dead woman''s real Loyalist operation was already dismantled, so the correction has no operational downside.',
 'An innocent woman avoids arrest. Fenwick becomes a cautious inside contact. No material reward — the reward is that nothing bad happened to someone it would have.'),

-- MIREPOST
('Dara''s Husband', 'mirepost-dara', 'Aranthor', 'town', 'available',
 'Pell Corden hasn''t been to the Mirepost Inn for three evenings. Innkeeper Vera Casse mentions it the moment players arrive. His wife Dara is at home.',
 'Pell is 30 days into Pale Wanderer early-stage. He is functional, eats when reminded, answers questions directly — and is peaceful in a way that makes the urgency around him feel mistaken. The Sentinel Order protocol: removal from influence zone, four weeks at distance, significant recovery expected. Window is closing. Generic reasons slide off him. Specific true things — his daughter''s name said like it matters, the work he cared about, Dara''s voice saying something only she would say — can reach him. If players leave and return: Day 1 update, he''s leaving the house at night. Day 2, he came back at dawn but doesn''t remember leaving. After that, Dara doesn''t know where he is. Run the clock honestly.',
 'Pell Corden — if saved, a reliable guide to the Veilwood edge and the northern road. More important: Dara, who has been watching Mirepost''s edges for a year and will tell players everything she knows.'),

('The Mayor''s Letters', 'mirepost-letters', 'Aranthor', 'town', 'available',
 'Mayor Oswin Hale has sent twelve reports to the Vaelthorn Regional Council over fourteen months documenting the Veilwood situation. A Vaelthorn clerk he knows told him this week: nine of the reports never arrived.',
 'A Blackwell-aligned administrative clerk at the Dunmore checkpoint has been intercepting Mirepost''s official correspondence for six months on behalf of Caedric''s intelligence apparatus — they don''t want Shadow Lord activity formally documented before they control the narrative. The clerk is holding the reports in a locked box, unopened. He will give up the box without significant resistance if confronted; he didn''t sign up for confrontation. The box contains Hale''s eleven reports plus three other suppressed letters: a Sentinel Order medical supply request, a Vaelthorn family letter seeking Pell Corden (connects TQ-MP1), and a legitimate trade complaint. All of Elyndra''s documentation work would benefit from the reports.',
 'Twelve months of careful Veilwood expansion data delivered to the Sentinel Order. Hale becomes an active ally — he has been waiting for someone to read what he wrote.'),

-- SYLVARA
('What Dalan Found', 'sylvara-dalan', 'Aranthor', 'town', 'available',
 'Dalan, the Sentinel Archive''s restricted-section archivist, found a file two weeks ago that he cannot explain. He mentions it to players passing through — not as a request, but as the unburdening of someone sitting alone with something uncomfortable.',
 'The file is a sealed genealogical record connecting the Vaelmont bloodline to a fifth Founding House lineage thought extinct for 300 years. Refiled in the restricted section thirty years ago — two years before the Night of Broken Glass. Contains a reference to a secondary claimant line relevant to the reforging. Three days after Dalan mentions it, a request arrives from Cale''s office in Caldrath asking the archive to confirm genealogical records related to the Vaelmont bloodline. The timing is wrong. Options: copy it (Dalan will allow with Elyndra''s trust), report to Elyndra (she acts; significant consequences), pass to Cale''s request (what Cale is looking for; complex), or hold it. This is not the last word on the bloodline question — but it changes what questions are being asked.',
 'A significant piece of the reforging puzzle. Dalan as a long-term archive contact who will flag things that matter. If passed to Elyndra: Sentinel Order gains critical genealogical intelligence.'),

-- DAWNHARBOR (second quest)
('The Harbormistress''s Ledger', 'dawnharbor-ledger', 'Sapphire Coast', 'town', 'available',
 'Harbormistress Rael Corde has kept a personal record of ships passing through Dawnharbor under false manifests for three years. 64 entries. No authority to act. She has been waiting for someone to give them to.',
 'The 64th entry: a ship that came in dark six days ago, docked four hours, left. Hull markings Rael noted through her glass don''t match the official manifest — the ship was supposedly moored in Tidecrest for two weeks. The Thornwall Runner connects to a Black Rose smuggling route using the Sapphire Coast as a blind-traffic corridor. But the 64 entries, analyzed, reveal TWO operations: Black Rose (legitimate intelligence work) and a second operation with different ship types and timing that doesn''t match Black Rose patterns — Cabal trade network signature. Both Selene and Elyndra would want this. The ledger''s analysis is the hard part; the intelligence is significant.',
 'Rael''s full 64-entry ledger — significant intelligence for Fog and Freedom and Black Rose Thorns campaigns. Rael as a reliable Sapphire Coast contact who will continue building the record.'),

-- TIDECREST
('The Missing Trade Log', 'tidecrest-trade-log', 'Sapphire Coast', 'town', 'available',
 'The Tidecrest customs office is missing four months of trade logs — not misfiled, not lost. Removed. Young customs officer Bren Solvin has received contradictory instructions from the two people above him and is quietly terrified.',
 'The logs cover the period when the Thornwall Runner (from Dawnharbor Ledger) was falsely documented as moored in Tidecrest. The key belongs to three people; Bren''s two superiors gave contradictory instructions — one told him to file a theft report, one said it was a clerical relocation. One is lying. The logs are in a locked chest at the home of a retired maritime administrator who is a Black Rose intermediary: he was asked to hold something temporarily and it became complicated. He''ll return the logs if approached carefully — will not give up his contact without DC 16 Persuasion or proof they''ve already burned him (DC 12). The combined Dawnharbor + Tidecrest thread reveals the scale of the Cabal operation.',
 'The missing four months of trade logs — combined with Rael''s ledger, documents the Cabal''s Sapphire Coast operation. Bren Solvin as a customs contact.'),

-- CINDERPOST
('The Relay Post', 'cinderpost-relay', 'Ashen Marches', 'town', 'available',
 'The post-rider handling Cinderpost''s mail route has been missing for eleven days. The substitute rode the route and returned in three days. She said: "The route is fine. I don''t know why he hasn''t come back. I would not go back to find out."',
 'Post-rider Orl stopped at his midpoint shelter on Day 5. The shelter log confirms he arrived and left. Between that shelter and Cinderpost: a section showing low-level void seepage effects for four months — disorientation, false path impressions, the feeling you''ve walked this stretch before. Orl is alive. He is at the midpoint shelter again — he has been going in circles for nine days and returning without understanding why. Low on food, eating his horse''s feed. DC 12 Arcana/Survival per hour to navigate the disorientation. The seepage is NEW — this corridor wasn''t affected four months ago. Updated boundary = important data for The Hungry Dark timeline.',
 'Orl''s safe return — he knows the western Marches corridor better than anyone and will now tell people about that stretch without being asked. Updated void seepage boundary data for Elyndra and the Ashval council.'),

-- COLDRUN
('The Missing Patrol', 'coldrun-patrol', 'Dreadspire Peaks', 'town', 'available',
 'A four-person patrol out of Coldrun went into the lower peaks eleven days ago and hasn''t returned. Standard patrol duration: four days. Captain Seld tells players this immediately upon arrival — he has been telling everyone who arrives for four days.',
 'Sergeant Reva Halden found an "inactive secondary resonance site" that is no longer inactive — a sealed Shadow Lord reach point. She sealed the cave entrance at a natural resonance gap (better work than she knew) and sent her fastest runner back. The runner got halfway and turned around because he felt strongly he should check on Reva. He is also at the camp now. The patrol is fine: cold, hungry, increasingly worried. DC 14 Arcana to assess the seal — it will hold two more weeks without maintenance. Reporting to Elyndra gets a proper Sentinel team dispatched; the threat level doesn''t require heroics, just equipment. The site is flagged. Reva comes back.',
 'Seld''s genuine gratitude. A documented new Shadow Lord reach point in the Dreadspire region — significant for the campaign''s seal-break map. Reva Halden as a contact with both Sentinel Order training and Peaks knowledge.'),

-- CALDRATH
('The Twelve in Transit', 'caldrath-twelve', 'Darian Empire', 'town', 'available',
 'Mira has twelve tieflings who need to move from the Registered Quarter to the harbor by Wednesday night. She tells players this without preamble as a test: yes or no, no conditions, decide now.',
 'Four problems to solve: (1) New Blackguard checkpoint on the usual route — tailor Pol knows an alternate but won''t confirm it to strangers without Mira''s intro (loop to break by talking to Pol first). (2) The warehouse manager is sick; someone must manage the handoff without knowing what it''s for. (3) Two of the twelve are children under eight — not a problem to solve, a constraint to accommodate. Watch how players respond to this. (4) Harbor contact isn''t responding to the Wednesday signal — surveillance or mundane? Must be checked without drawing attention. Mira held back the harbor contact info until Tuesday morning; she knew he was fine but watched how players handled uncertainty. All four problems have solutions. No violence needed.',
 'Mira''s trust — the most valuable resource in Caldrath''s underground. Access to the full Census Cheats network. Specific intelligence from Mira''s operational picture.'),

('The 848th Name', 'caldrath-cale', 'Darian Empire', 'town', 'available',
 'High Chancellor Cale has a problem he cannot solve through the mechanism he has used for 847 others. A woman named Tessara Vyn has been formally flagged — three citations, one open enforcement case — and any record alteration would trigger an automatic audit that would expose the entire third list.',
 'Three paths, each resolving the enforcement case through legitimate means: (1) Administrative — one citation was issued by an officer whose cases are in review for procedural violations. DC 13 Investigation to find the review record; standard filing once found. (2) Medical — one citation from a missed registration Tessara missed because she was admitted to a medical facility the same day. The record exists, wasn''t included due to clerical error. Obtain and file correctly. (3) Procedural — the open enforcement case uses old ordinance text; an 18-month-old amendment means Tessara''s situation no longer meets threshold. Find the amendment citation and give the case officer an exit. He''ll take it. He''s not a zealot. Players don''t need to solve all three — one is enough. Tessara never knows who helped.',
 'One piece of intelligence from Cale''s full picture — whatever is most relevant to the campaign''s current thread. The knowledge that there are 847 other names on that list, and what that means about Cale.'),

('The Public Audience', 'caldrath-audience', 'Darian Empire', 'town', 'available',
 'Emperor Caelan Darius IV holds public audience on the third day of each month. An Aranthorian woman named Hessa Brint has documented evidence of a Pale Choir village dissolution and needs to deliver it directly — every official channel has either redirected or stopped responding. She has nine days.',
 'The petition system has seven required forms. Four reference each other in a loop created by a procedural conflict 18 years ago and never resolved. Senior aide Prissian (22 years in this job) will explain the correct navigation to anyone who asks politely. The key: file Form 7-C before Form 7-A. DC 12 Investigation to find this, or ask Prissian directly. At the audience, the Emperor asks three specific questions that reveal he understands what he''s being told. Two weeks later a Legion survey team is dispatched to the location Hessa marked. This is how things move through a functioning bureaucracy.',
 'A Legion survey team confirmed for Hessa''s documented location. The Emperor''s attention added to the Shadow Lord category — observable in how he subsequently receives information about it. Hessa''s gratitude (one drink each, pre-budgeted).'),

-- IRONWATCH
('The Forty-Three', 'ironwatch-refugees', 'Darian Empire', 'town', 'available',
 'The refugee count at Ironwatch''s holding area is now forty-three. The newest arrival is a child, approximately six, alone, who gave her name as "Mira" and hasn''t spoken since. Colonel Dawn has been feeding these people for ninety-three days with no protocol guidance.',
 'Three paths: Political — players with access to Cale or the Emperor can create a formal temporary sanctuary designation, giving Dawn the authority she needs. Practical — established safe zones in Aranthor can receive them (logistics: 43 people, some injured, two days with organizational help). Individual — specific people in the holding area: a family trying to reach Trade Quarter relatives; a Sentinel Order contact who has been trying to signal his identity for three weeks; a healer who could be immediately useful in Ironwatch and would prefer to stay. The child called Mira is not connected to the Caldrath underground leader — she gave the first name she heard. Her village no longer has enough residents to be a village. Dawn handles this with the practicality of someone who doesn''t allow herself to feel things while on duty.',
 'Forty-three people with somewhere to go. Colonel Dawn as a border military ally who can provide transit papers, intelligence relay, and quiet checkpoint blindness. The Sentinel Order contact''s identity and information.'),

('The Broker''s Problem', 'ironwatch-broker', 'Darian Empire', 'town', 'available',
 'Black Rose cloth merchant Arvis has a sealed package he cannot move — his usual inspection officer was rotated out and replaced by someone honest. He has been sitting on it three weeks. The package''s sender has limited patience.',
 'The package contains confirmation documentation for a Blackwell-Cabal coordination meeting — a cleaner version of the evidence referenced in the Gerta Foss story from Dunmore. Players who have both pieces can cross-reference: the combined documentation is significantly more powerful. Arvis doesn''t know what''s in it (professional principle, also survival strategy). Options: carry personally (DC 13 Deception if specifically questioned), alternate wilderness route (monitored, DC 15 Survival), or help Arvis establish a new inspector arrangement (two conversations, Arvis handles negotiation, players provide introduction). The package reaches Vaelthorn either way.',
 'Arvis as an operational Black Rose border contact. Combined Dunmore + Ironwatch documentation of Blackwell-Cabal meeting. Access to cross-border message routing for future campaign needs.'),

-- STONEFALL
('The Soldier''s Complaint', 'stonefall-complaint', 'Darian Empire', 'town', 'available',
 'Garrison soldier Brek filed a formal complaint three weeks ago about irregular activity near the Blackguard section. Sounds at odd hours. Personnel in unmarked clothing moving supplies after midnight. A smell he couldn''t name. The complaint is on Major Thorn''s desk. She has not acted on it.',
 'Thorn hasn''t acted because acting means knowing means being responsible. Three years to retirement, clean record, eight years of the same internal conversation. Brek''s complaint is forcing it onto a desk. Three approaches: help Brek understand what he observed (the smell matches a specific compound used in the Undercroft''s interrogation rooms — requires someone who knows what the Undercroft is); bring Thorn the information she''s been not-looking-for (requires evidence or trust); find the sergeant whose personal log documents seventeen irregularities in a bunk-kept notebook. If players reach Thorn with actual information: the moment when a decision made for eight years stops holding. She is not bad. She makes the choice anyway, eventually.',
 'Major Thorn''s conscience, activated. A garrison ally who can provide Stonefall surface access and will not obstruct Undercroft investigation. Brek''s uncomplicated gratitude and knowledge of garrison patterns.'),

('The Night Schedule', 'stonefall-schedule', 'Darian Empire', 'town', 'available',
 'Before the Ironclad Undercroft mission: players need the Blackguard rotation schedule — specifically the timing and pattern of movement between the Blackguard barracks and the Drop Gate access. Three people in Stonefall have this information without knowing it''s being sought.',
 'Fenno at the Ironpot has watched the "special logistics staff" for two years out of barkeep habit: they go quiet on the third and fourth nights of each week, rotate shift change at second bell after midnight instead of first, always check the east perimeter fence twice before late shift ends. 2 sp gets everything he knows. Healer Voss treated two Blackguard injuries in three years — both in early morning hours on non-standard days, both patients uncommunicative; one was shaking. Timing corresponds to specific Undercroft interrogation sessions. Direct observation: 2 hours, DC 14 Perception/Investigation for standard pattern; DC 16 to note Warden Solt''s solo oversight rounds (irregular nights, 1-3 hours, no standard rotation). All three sources are non-conspiratorial — people with partial pictures and human patterns.',
 'Blackguard rotation schedule. Warden Solt''s personal pattern if DC 16 achieved. A picture of the gap between Stonefall''s garrison and the Blackguard section that makes Undercroft infiltration viable.'),

-- IRON BASTION
('Vane''s Offer', 'iron-bastion-vane', 'Darian Empire', 'town', 'available',
 'General Aldric Vane has three open questions about the Aranthorian situation his intelligence network cannot answer from inside the Empire. Players who arrive with firsthand experience are the confirmation he has been waiting for.',
 'He will give his full intelligence picture — three years of accumulated reforging, Shadow Lord, succession, and Imperial strategic information — in exchange for honest answers to three questions. The picture is worth more than the answers; he knows this. Three questions: (1) Is the Pale Choir expansion rate symmetric or directional? He needs comparison from someone who has been in both zones. (2) Can players confirm or deny his four suspected-but-unconfirmed Seal break sites from their travels? (3) Is there a working succession candidate with actual coalition AND Founding bloodline component, or is the political solution still open? He updates his model immediately and without defensiveness when given sufficient evidence. At the end he says: "You should talk to the Emperor. I will arrange it if you want me to."',
 'Vane''s full three-year intelligence picture — the most complete Imperial assessment of the Shadow Lord threat available. A direct path to the Emperor for late-campaign access. Vane as a reliable Imperial military intelligence contact.'),

('The Survey''s Finding', 'iron-bastion-survey', 'Darian Empire', 'town', 'available',
 'Commander Elara Denn''s Arcane Vanguard survey has found a major ley-node anomaly in Aranthor consistent with Shadow Lord seal degradation. She cannot send a team across the border. She needs a physical sample — a resonance-recording crystal charged at the site.',
 'The site is 3 days'' travel into the Ashen Marches, near the grey zone edge. No hostile forces — the hazard is passive void seepage: DC 12 Wisdom saves per hour near the node, increasing disorientation on failure. Players with void-resistance or Sentinel Order training are better positioned. The 30 minutes of crystal recording can be done from 200 meters. If players show the results to both Denn and Elyndra: two researchers who have been independently documenting the same problem from opposite sides of the border discover their work confirms each other''s conclusions. This is the moment the Empire''s and the Sentinel Order''s assessments align. Vane is told within 24 hours. The crystal''s secondary data (what the resonance filter doesn''t cover) is the part Denn doesn''t know about yet.',
 'Denn''s research confirmed and extended — she provides a full analysis of the crystal data within one week. Elyndra + Denn collaboration opened. The specific unknown that the secondary data reveals, which neither researcher had in their model.')

ON CONFLICT (slug) DO NOTHING;
